-- Minimal legacy schema for isolated migration tests; never run against production.
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
CREATE ROLE authenticated;
CREATE TABLE public.users (id uuid PRIMARY KEY, role text);
CREATE TABLE public.impact_indicators (id bigint PRIMARY KEY, indicator_code text, indicator_title text, indicator_unit text);
CREATE TABLE public.outcome_measurables (id bigint PRIMARY KEY, project_id bigint, impact_indicator_id bigint REFERENCES impact_indicators);
CREATE TABLE public.output_measurables (id bigint PRIMARY KEY, project_id bigint, impact_indicator_id bigint REFERENCES impact_indicators);
CREATE TABLE public.updates (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id bigint, output_measurable_id bigint REFERENCES output_measurables, impact_indicator_id bigint REFERENCES impact_indicators, posted_by uuid, type text, description text, value double precision, link text, source text, date date, year integer, created_at timestamptz DEFAULT now(), edited_at timestamptz, valid boolean DEFAULT true, verified boolean DEFAULT false, duplicate boolean DEFAULT false, admin_reviewed boolean DEFAULT false, review_note text);
INSERT INTO users VALUES ('00000000-0000-0000-0000-000000000001', 'Admin'), ('00000000-0000-0000-0000-000000000002', 'Partner');
INSERT INTO impact_indicators VALUES (1, '1.1.1', 'MPAs', 'MPAs'), (2, '1.1.2', 'Area', 'km2');
INSERT INTO outcome_measurables VALUES (1, 1, 1);
INSERT INTO output_measurables VALUES (1, 1, 1);
GRANT USAGE ON SCHEMA public, auth TO authenticated;
GRANT SELECT ON users, impact_indicators TO authenticated;
GRANT SELECT, INSERT, UPDATE ON updates, outcome_measurables, output_measurables TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
