// This file is generated by scripts/generate-project-geographies.mjs.
// Source: Natural Earth ca96624a56bd078437bca8184e78163e5039ad19 (public domain).
// XKS and XSB are included only after live verification against Mapbox Countries v1.
// Do not edit this file by hand.

export type GeneratedIsoGeography = {
  iso3: string;
  label: string;
  bounds: [[number, number], [number, number]];
  renderAsPoint: boolean;
  markerCoordinates: [number, number] | null;
};

export const GENERATED_ISO_SOURCE = {
  naturalEarthCommit: 'ca96624a56bd078437bca8184e78163e5039ad19',
  officialIsoEntries: 249,
  mapboxVerifiedExtras: ['XKS', 'XSB'],
} as const;

export const GENERATED_ISO_GEOGRAPHIES: GeneratedIsoGeography[] = [
  {
    iso3: 'AFG',
    label: 'Afghanistan',
    bounds: [
      [60.486778, 29.386605],
      [74.892307, 38.473673],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ALA',
    label: 'Åland',
    bounds: [
      [19.513194, 59.904486],
      [21.09669, 60.48078],
    ],
    renderAsPoint: true,
    markerCoordinates: [19.869671, 60.156467],
  },
  {
    iso3: 'ALB',
    label: 'Albania',
    bounds: [
      [19.272033, 39.637013],
      [21.036679, 42.654814],
    ],
    renderAsPoint: true,
    markerCoordinates: [20.11384, 40.654855],
  },
  {
    iso3: 'DZA',
    label: 'Algeria',
    bounds: [
      [-8.682385, 18.975561],
      [11.968861, 37.09394],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ASM',
    label: 'American Samoa',
    bounds: [
      [-171.086537, -14.532892],
      [-168.160471, -11.051365],
    ],
    renderAsPoint: true,
    markerCoordinates: [-170.747153, -14.32671],
  },
  {
    iso3: 'AND',
    label: 'Andorra',
    bounds: [
      [1.406456, 42.428677],
      [1.765091, 42.649362],
    ],
    renderAsPoint: true,
    markerCoordinates: [1.539409, 42.547643],
  },
  {
    iso3: 'AGO',
    label: 'Angola',
    bounds: [
      [11.669394, -18.031405],
      [24.061714, -4.391204],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'AIA',
    label: 'Anguilla',
    bounds: [
      [-63.428822, 18.169094],
      [-62.925682, 18.601264],
    ],
    renderAsPoint: true,
    markerCoordinates: [-63.026361, 18.242979],
  },
  {
    iso3: 'ATA',
    label: 'Antarctica',
    bounds: [
      [-180, -90],
      [180, -60],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ATG',
    label: 'Antigua and Barbuda',
    bounds: [
      [-62.34826, 16.93197],
      [-61.667592, 17.727688],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.806764, 17.076401],
  },
  {
    iso3: 'ARG',
    label: 'Argentina',
    bounds: [
      [-73.57274, -55.052016],
      [-53.661552, -21.786938],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ARM',
    label: 'Armenia',
    bounds: [
      [43.436294, 38.863701],
      [46.602612, 41.290452],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ABW',
    label: 'Aruba',
    bounds: [
      [-70.062408, 12.41767],
      [-69.87682, 12.632148],
    ],
    renderAsPoint: true,
    markerCoordinates: [-69.972795, 12.5174],
  },
  {
    iso3: 'AUS',
    label: 'Australia',
    bounds: [
      [112.919444, -54.750421],
      [159.106456, -9.240167],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'AUT',
    label: 'Austria',
    bounds: [
      [9.521155, 46.378643],
      [17.148338, 49.009774],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'AZE',
    label: 'Azerbaijan',
    bounds: [
      [44.774559, 38.392645],
      [50.625743, 41.890442],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BHR',
    label: 'Bahrain',
    bounds: [
      [50.38053, 25.579891],
      [50.819875, 26.287439],
    ],
    renderAsPoint: true,
    markerCoordinates: [50.554816, 26.055972],
  },
  {
    iso3: 'BGD',
    label: 'Bangladesh',
    bounds: [
      [88.02179, 20.738715],
      [92.642851, 26.623544],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BRB',
    label: 'Barbados',
    bounds: [
      [-59.654205, 13.051174],
      [-59.42691, 13.34455],
    ],
    renderAsPoint: true,
    markerCoordinates: [-59.568966, 13.163709],
  },
  {
    iso3: 'BLR',
    label: 'Belarus',
    bounds: [
      [23.165645, 51.235168],
      [32.719532, 56.156806],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BEL',
    label: 'Belgium',
    bounds: [
      [2.5218, 49.495223],
      [6.374525, 51.496238],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BLZ',
    label: 'Belize',
    bounds: [
      [-89.236512, 15.879652],
      [-87.78307, 18.490759],
    ],
    renderAsPoint: true,
    markerCoordinates: [-88.712962, 17.202068],
  },
  {
    iso3: 'BEN',
    label: 'Benin',
    bounds: [
      [0.759881, 6.213894],
      [3.837419, 12.399244],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BMU',
    label: 'Bermuda',
    bounds: [
      [-64.885994, 32.248077],
      [-64.647631, 32.388658],
    ],
    renderAsPoint: true,
    markerCoordinates: [-64.763573, 32.296592],
  },
  {
    iso3: 'BTN',
    label: 'Bhutan',
    bounds: [
      [88.730067, 26.696149],
      [92.088776, 28.358399],
    ],
    renderAsPoint: true,
    markerCoordinates: [90.040294, 27.536685],
  },
  {
    iso3: 'BOL',
    label: 'Bolivia',
    bounds: [
      [-69.666492, -22.897258],
      [-57.465661, -9.679821],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BIH',
    label: 'Bosnia and Herzegovina',
    bounds: [
      [15.716074, 42.559212],
      [19.618885, 45.284524],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BWA',
    label: 'Botswana',
    bounds: [
      [19.978346, -26.891794],
      [29.350074, -17.781808],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BVT',
    label: 'Bouvet Island',
    bounds: [
      [3.345551, -54.462498],
      [3.486664, -54.380141],
    ],
    renderAsPoint: true,
    markerCoordinates: [3.414486, -54.415335],
  },
  {
    iso3: 'BRA',
    label: 'Brazil',
    bounds: [
      [-74.018475, -33.74228],
      [-28.877065, 5.267225],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IOT',
    label: 'British Indian Ocean Territory',
    bounds: [
      [71.260997, -7.432224],
      [72.49464, -5.226983],
    ],
    renderAsPoint: true,
    markerCoordinates: [71.348349, -6.190826],
  },
  {
    iso3: 'VGB',
    label: 'British Virgin Islands',
    bounds: [
      [-64.773997, 18.334662],
      [-64.270741, 18.746243],
    ],
    renderAsPoint: true,
    markerCoordinates: [-64.63661, 18.426606],
  },
  {
    iso3: 'BRN',
    label: 'Brunei',
    bounds: [
      [113.99879, 4.016681],
      [115.360741, 5.057196],
    ],
    renderAsPoint: true,
    markerCoordinates: [114.551943, 4.448298],
  },
  {
    iso3: 'BGR',
    label: 'Bulgaria',
    bounds: [
      [22.345023, 41.238104],
      [28.603526, 44.228435],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BFA',
    label: 'Burkina Faso',
    bounds: [
      [-5.522578, 9.391883],
      [2.390169, 15.079908],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BDI',
    label: 'Burundi',
    bounds: [
      [28.986892, -4.463344],
      [30.833962, -2.303062],
    ],
    renderAsPoint: true,
    markerCoordinates: [29.917086, -3.332836],
  },
  {
    iso3: 'KHM',
    label: 'Cambodia',
    bounds: [
      [102.313424, 10.415774],
      [107.610516, 14.704582],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CMR',
    label: 'Cameroon',
    bounds: [
      [8.505056, 1.654551],
      [16.207723, 13.081141],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CAN',
    label: 'Canada',
    bounds: [
      [-141.005564, 41.669086],
      [-52.616607, 83.116523],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CPV',
    label: 'Cape Verde',
    bounds: [
      [-25.360422, 14.803941],
      [-22.666575, 17.196601],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BES',
    label: 'Caribbean Netherlands',
    bounds: [
      [-68.417388, 12.02204],
      [-62.945065, 17.646918],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CYM',
    label: 'Cayman Islands',
    bounds: [
      [-81.416542, 19.263864],
      [-79.726643, 19.757631],
    ],
    renderAsPoint: true,
    markerCoordinates: [-81.24055, 19.319862],
  },
  {
    iso3: 'CAF',
    label: 'Central African Republic',
    bounds: [
      [14.387266, 2.236454],
      [27.441301, 11.000828],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TCD',
    label: 'Chad',
    bounds: [
      [13.449184, 7.455567],
      [23.984406, 23.44472],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CHL',
    label: 'Chile',
    bounds: [
      [-109.453725, -55.918504],
      [-66.420806, -17.506588],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CXR',
    label: 'Christmas Island',
    bounds: [
      [105.581798, -10.566013],
      [105.714692, -10.430841],
    ],
    renderAsPoint: true,
    markerCoordinates: [105.67259, -10.490789],
  },
  {
    iso3: 'CCK',
    label: 'Cocos',
    bounds: [
      [96.821544, -12.199965],
      [96.921072, -12.12656],
    ],
    renderAsPoint: true,
    markerCoordinates: [96.830147, -12.159615],
  },
  {
    iso3: 'COL',
    label: 'Colombia',
    bounds: [
      [-81.723704, -4.236484],
      [-66.875061, 13.578355],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'COM',
    label: 'Comoros',
    bounds: [
      [43.213227, -12.380304],
      [44.529063, -11.361261],
    ],
    renderAsPoint: true,
    markerCoordinates: [43.318094, -11.727683],
  },
  {
    iso3: 'COK',
    label: 'Cook Islands',
    bounds: [
      [-165.824534, -21.938897],
      [-157.312815, -8.94671],
    ],
    renderAsPoint: true,
    markerCoordinates: [-159.785675, -21.215993],
  },
  {
    iso3: 'CRI',
    label: 'Costa Rica',
    bounds: [
      [-87.117665, 5.515082],
      [-82.562837, 11.209937],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'HRV',
    label: 'Croatia',
    bounds: [
      [13.501475, 42.416327],
      [19.407838, 46.546979],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CUB',
    label: 'Cuba',
    bounds: [
      [-84.949615, 19.827826],
      [-74.132883, 23.26557],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CUW',
    label: 'Curaçao',
    bounds: [
      [-69.171742, 12.041327],
      [-68.739735, 12.391506],
    ],
    renderAsPoint: true,
    markerCoordinates: [-68.920578, 12.145039],
  },
  {
    iso3: 'CYP',
    label: 'Cyprus',
    bounds: [
      [32.271739, 34.625019],
      [34.099132, 35.187082],
    ],
    renderAsPoint: true,
    markerCoordinates: [33.084182, 34.913329],
  },
  {
    iso3: 'CZE',
    label: 'Czech Republic',
    bounds: [
      [12.076141, 48.557916],
      [18.837434, 51.040012],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'COD',
    label: 'Democratic Republic of the Congo',
    bounds: [
      [12.210541, -13.458351],
      [31.280447, 5.37528],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'DNK',
    label: 'Denmark',
    bounds: [
      [8.094005, 54.56859],
      [15.151378, 57.751166],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'DJI',
    label: 'Djibouti',
    bounds: [
      [41.74911, 10.929825],
      [43.418712, 12.707913],
    ],
    renderAsPoint: true,
    markerCoordinates: [42.498825, 11.976343],
  },
  {
    iso3: 'DMA',
    label: 'Dominica',
    bounds: [
      [-61.488922, 15.201809],
      [-61.249257, 15.633857],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.344958, 15.458829],
  },
  {
    iso3: 'DOM',
    label: 'Dominican Republic',
    bounds: [
      [-72.009838, 17.545559],
      [-68.328603, 19.93769],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TLS',
    label: 'East Timor',
    bounds: [
      [124.03004, -9.501228],
      [127.313243, -8.135024],
    ],
    renderAsPoint: true,
    markerCoordinates: [125.854679, -8.803705],
  },
  {
    iso3: 'ECU',
    label: 'Ecuador',
    bounds: [
      [-92.011586, -5.011373],
      [-75.227264, 1.664374],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'EGY',
    label: 'Egypt',
    bounds: [
      [24.688343, 21.994369],
      [36.899181, 31.65648],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SLV',
    label: 'El Salvador',
    bounds: [
      [-90.114779, 13.158637],
      [-87.693194, 14.445373],
    ],
    renderAsPoint: true,
    markerCoordinates: [-88.890124, 13.685371],
  },
  {
    iso3: 'GNQ',
    label: 'Equatorial Guinea',
    bounds: [
      [5.61199, -1.475681],
      [11.336341, 3.772406],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ERI',
    label: 'Eritrea',
    bounds: [
      [36.423647, 12.360022],
      [43.123871, 18.004828],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'EST',
    label: 'Estonia',
    bounds: [
      [21.832367, 57.515819],
      [28.186475, 59.670885],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SWZ',
    label: 'Eswatini',
    bounds: [
      [30.782906, -27.316264],
      [32.117398, -25.735999],
    ],
    renderAsPoint: true,
    markerCoordinates: [31.467264, -26.533676],
  },
  {
    iso3: 'ETH',
    label: 'Ethiopia',
    bounds: [
      [32.9898, 3.403333],
      [47.979169, 14.879532],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'FLK',
    label: 'Falkland Islands',
    bounds: [
      [-61.318186, -52.406523],
      [-57.734283, -51.027765],
    ],
    renderAsPoint: true,
    markerCoordinates: [-58.738602, -51.608913],
  },
  {
    iso3: 'FRO',
    label: 'Faroe Islands',
    bounds: [
      [-7.644154, 61.39411],
      [-6.275787, 62.398912],
    ],
    renderAsPoint: true,
    markerCoordinates: [-7.058429, 62.185604],
  },
  {
    iso3: 'FSM',
    label: 'Federated States of Micronesia',
    bounds: [
      [138.063813, 0.918158],
      [163.04656, 9.77558],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'FJI',
    label: 'Fiji',
    bounds: [
      [174.588878, -21.711114],
      [181.783865, -12.475274],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'FIN',
    label: 'Finland',
    bounds: [
      [20.623165, 59.811225],
      [31.569525, 70.07531],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'FRA',
    label: 'France',
    bounds: [
      [-109.234242, 10.281562],
      [9.559581, 51.087541],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GUF',
    label: 'French Guiana',
    bounds: [
      [-54.615292, 2.110673],
      [-51.649037, 5.744765],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PYF',
    label: 'French Polynesia',
    bounds: [
      [-154.536977, -27.641209],
      [-134.942983, -7.950128],
    ],
    renderAsPoint: true,
    markerCoordinates: [-149.46157, -17.628081],
  },
  {
    iso3: 'ATF',
    label: 'French Southern and Antarctic Lands',
    bounds: [
      [39.728282, -49.721612],
      [77.585216, -11.550632],
    ],
    renderAsPoint: true,
    markerCoordinates: [69.122136, -49.303721],
  },
  {
    iso3: 'GAB',
    label: 'Gabon',
    bounds: [
      [8.695567, -3.936856],
      [14.498991, 2.322495],
    ],
    renderAsPoint: true,
    markerCoordinates: [11.835939, -0.437739],
  },
  {
    iso3: 'GEO',
    label: 'Georgia',
    bounds: [
      [39.985976, 41.044111],
      [46.694803, 43.575843],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'DEU',
    label: 'Germany',
    bounds: [
      [5.85249, 47.271121],
      [15.022059, 55.065334],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GHA',
    label: 'Ghana',
    bounds: [
      [-3.262509, 4.737128],
      [1.187968, 11.162937],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GIB',
    label: 'Gibraltar',
    bounds: [
      [-5.358387, 36.1105],
      [-5.338773, 36.14112],
    ],
    renderAsPoint: true,
    markerCoordinates: [-5.3467, 36.129426],
  },
  {
    iso3: 'GRC',
    label: 'Greece',
    bounds: [
      [19.626475, 34.815009],
      [28.239757, 41.750476],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GRL',
    label: 'Greenland',
    bounds: [
      [-73.05724, 59.792629],
      [-11.37682, 83.634101],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GRD',
    label: 'Grenada',
    bounds: [
      [-61.790517, 12.002834],
      [-61.42162, 12.529731],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.680461, 12.113156],
  },
  {
    iso3: 'GLP',
    label: 'Guadeloupe',
    bounds: [
      [-61.797841, 15.846991],
      [-60.989247, 16.513088],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.433565, 16.299332],
  },
  {
    iso3: 'GUM',
    label: 'Guam',
    bounds: [
      [144.624197, 13.241034],
      [144.952159, 13.65412],
    ],
    renderAsPoint: true,
    markerCoordinates: [144.703614, 13.354173],
  },
  {
    iso3: 'GTM',
    label: 'Guatemala',
    bounds: [
      [-92.246257, 13.731404],
      [-88.220937, 17.81602],
    ],
    renderAsPoint: true,
    markerCoordinates: [-90.497134, 14.982133],
  },
  {
    iso3: 'GGY',
    label: 'Guernsey',
    bounds: [
      [-2.673451, 49.411566],
      [-2.170318, 49.731391],
    ],
    renderAsPoint: true,
    markerCoordinates: [-2.561736, 49.463533],
  },
  {
    iso3: 'GIN',
    label: 'Guinea',
    bounds: [
      [-15.081125, 7.190208],
      [-7.662447, 12.673388],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GNB',
    label: 'Guinea-Bissau',
    bounds: [
      [-16.728437, 10.927639],
      [-13.660712, 12.679434],
    ],
    renderAsPoint: true,
    markerCoordinates: [-14.52413, 12.163712],
  },
  {
    iso3: 'GUY',
    label: 'Guyana',
    bounds: [
      [-61.396713, 1.18582],
      [-56.481819, 8.55801],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'HTI',
    label: 'Haiti',
    bounds: [
      [-74.489166, 18.025946],
      [-71.639111, 20.089789],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'HMD',
    label: 'Heard Island and McDonald Islands',
    bounds: [
      [73.236013, -53.19256],
      [73.812185, -52.961602],
    ],
    renderAsPoint: true,
    markerCoordinates: [73.50521, -53.103462],
  },
  {
    iso3: 'HND',
    label: 'Honduras',
    bounds: [
      [-89.363791, 12.979777],
      [-83.130444, 17.418647],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'HKG',
    label: 'Hong Kong',
    bounds: [
      [113.837332, 22.177069],
      [114.401296, 22.563946],
    ],
    renderAsPoint: true,
    markerCoordinates: [114.097769, 22.448829],
  },
  {
    iso3: 'HUN',
    label: 'Hungary',
    bounds: [
      [16.094035, 45.741343],
      [22.877601, 48.569233],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ISL',
    label: 'Iceland',
    bounds: [
      [-24.539906, 63.396715],
      [-13.502919, 66.564154],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IND',
    label: 'India',
    bounds: [
      [68.143403, 6.745551],
      [97.362253, 35.495406],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IDN',
    label: 'Indonesia',
    bounds: [
      [95.012706, -10.922621],
      [140.977627, 5.910102],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IRN',
    label: 'Iran',
    bounds: [
      [44.014863, 25.059408],
      [63.319628, 39.771527],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IRQ',
    label: 'Iraq',
    bounds: [
      [38.774511, 29.063137],
      [48.559255, 37.375498],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IRL',
    label: 'Ireland',
    bounds: [
      [-10.478179, 51.445705],
      [-5.99352, 55.386379],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'IMN',
    label: 'Isle of Man',
    bounds: [
      [-4.790151, 54.056952],
      [-4.31192, 54.419013],
    ],
    renderAsPoint: true,
    markerCoordinates: [-4.530069, 54.220833],
  },
  {
    iso3: 'ISR',
    label: 'Israel',
    bounds: [
      [34.248351, 29.489691],
      [35.888073, 33.406722],
    ],
    renderAsPoint: true,
    markerCoordinates: [34.847915, 30.911148],
  },
  {
    iso3: 'ITA',
    label: 'Italy',
    bounds: [
      [6.602728, 35.489244],
      [18.517426, 47.085215],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CIV',
    label: 'Ivory Coast',
    bounds: [
      [-8.61872, 4.344062],
      [-2.506328, 10.726478],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'JAM',
    label: 'Jamaica',
    bounds: [
      [-78.374664, 17.703192],
      [-76.187978, 18.525092],
    ],
    renderAsPoint: true,
    markerCoordinates: [-77.318767, 18.137124],
  },
  {
    iso3: 'JPN',
    label: 'Japan',
    bounds: [
      [122.938162, 24.212104],
      [153.985606, 45.520413],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'JEY',
    label: 'Jersey',
    bounds: [
      [-2.242014, 49.171332],
      [-2.00829, 49.267035],
    ],
    renderAsPoint: true,
    markerCoordinates: [-2.090146, 49.220808],
  },
  {
    iso3: 'JOR',
    label: 'Jordan',
    bounds: [
      [34.949385, 29.189951],
      [39.291999, 33.371685],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'KAZ',
    label: 'Kazakhstan',
    bounds: [
      [46.478279, 40.584656],
      [87.323796, 55.43455],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'KEN',
    label: 'Kenya',
    bounds: [
      [33.890468, -4.677504],
      [41.885019, 5.030376],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'KIR',
    label: 'Kiribati',
    bounds: [
      [169.522146, -11.461114],
      [208.219045, 4.72309],
    ],
    renderAsPoint: true,
    markerCoordinates: [-157.384577, 1.820437],
  },
  {
    iso3: 'XKS',
    label: 'Kosovo',
    bounds: [
      [20.024751, 41.84401],
      [21.772758, 43.263071],
    ],
    renderAsPoint: true,
    markerCoordinates: [20.860719, 42.593587],
  },
  {
    iso3: 'KWT',
    label: 'Kuwait',
    bounds: [
      [46.532436, 28.533505],
      [48.432781, 30.098216],
    ],
    renderAsPoint: true,
    markerCoordinates: [47.313999, 29.413628],
  },
  {
    iso3: 'KGZ',
    label: 'Kyrgyzstan',
    bounds: [
      [69.226296, 39.189237],
      [80.257561, 43.261702],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LAO',
    label: 'Laos',
    bounds: [
      [100.097073, 13.915457],
      [107.664363, 22.496044],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LVA',
    label: 'Latvia',
    bounds: [
      [20.968598, 55.666991],
      [28.217275, 58.075138],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LBN',
    label: 'Lebanon',
    bounds: [
      [35.09962, 33.05558],
      [36.604101, 34.687548],
    ],
    renderAsPoint: true,
    markerCoordinates: [35.992892, 34.133368],
  },
  {
    iso3: 'LSO',
    label: 'Lesotho',
    bounds: [
      [27.002155, -30.658799],
      [29.435908, -28.570761],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LBR',
    label: 'Liberia',
    bounds: [
      [-11.476186, 4.347235],
      [-7.384118, 8.565396],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LBY',
    label: 'Libya',
    bounds: [
      [9.286544, 19.496124],
      [25.156261, 33.181225],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LIE',
    label: 'Liechtenstein',
    bounds: [
      [9.475886, 47.0524],
      [9.615723, 47.262801],
    ],
    renderAsPoint: true,
    markerCoordinates: [9.559439, 47.111405],
  },
  {
    iso3: 'LTU',
    label: 'Lithuania',
    bounds: [
      [20.924569, 53.886841],
      [26.80072, 56.442602],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LUX',
    label: 'Luxembourg',
    bounds: [
      [5.714927, 49.441324],
      [6.502579, 50.174975],
    ],
    renderAsPoint: true,
    markerCoordinates: [6.07762, 49.733732],
  },
  {
    iso3: 'MAC',
    label: 'Macau',
    bounds: [
      [113.519867, 22.105373],
      [113.587494, 22.220771],
    ],
    renderAsPoint: true,
    markerCoordinates: [113.556038, 22.129735],
  },
  {
    iso3: 'MDG',
    label: 'Madagascar',
    bounds: [
      [43.222911, -25.598565],
      [50.503917, -11.943617],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MWI',
    label: 'Malawi',
    bounds: [
      [32.663308, -17.135335],
      [35.904299, -9.381235],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MYS',
    label: 'Malaysia',
    bounds: [
      [99.645228, 0.85137],
      [119.278087, 7.35578],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MDV',
    label: 'Maldives',
    bounds: [
      [72.684825, -0.688572],
      [73.753184, 7.107245],
    ],
    renderAsPoint: true,
    markerCoordinates: [73.507554, 4.174441],
  },
  {
    iso3: 'MLI',
    label: 'Mali',
    bounds: [
      [-12.26413, 10.140054],
      [4.235638, 24.995065],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MLT',
    label: 'Malta',
    bounds: [
      [14.183604, 35.801215],
      [14.567149, 36.075588],
    ],
    renderAsPoint: true,
    markerCoordinates: [14.433005, 35.892886],
  },
  {
    iso3: 'MHL',
    label: 'Marshall Islands',
    bounds: [
      [165.282237, 4.573798],
      [172.029796, 14.6105],
    ],
    renderAsPoint: true,
    markerCoordinates: [171.193609, 7.082568],
  },
  {
    iso3: 'MTQ',
    label: 'Martinique',
    bounds: [
      [-61.228831, 14.408108],
      [-60.810414, 14.876899],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.055657, 14.711979],
  },
  {
    iso3: 'MRT',
    label: 'Mauritania',
    bounds: [
      [-17.081175, 14.734399],
      [-4.821613, 27.285416],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MUS',
    label: 'Mauritius',
    bounds: [
      [56.524181, -20.517348],
      [63.493907, -10.323907],
    ],
    renderAsPoint: true,
    markerCoordinates: [57.565848, -20.299506],
  },
  {
    iso3: 'MYT',
    label: 'Mayotte',
    bounds: [
      [45.042491, -12.98919],
      [45.290863, -12.647231],
    ],
    renderAsPoint: true,
    markerCoordinates: [45.151319, -12.774755],
  },
  {
    iso3: 'MEX',
    label: 'Mexico',
    bounds: [
      [-118.368804, 14.546279],
      [-86.700592, 32.712836],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MDA',
    label: 'Moldova',
    bounds: [
      [26.617889, 45.461774],
      [30.131576, 48.486034],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MCO',
    label: 'Monaco',
    bounds: [
      [7.36575, 43.717969],
      [7.437454, 43.763506],
    ],
    renderAsPoint: true,
    markerCoordinates: [7.398291, 43.739652],
  },
  {
    iso3: 'MNG',
    label: 'Mongolia',
    bounds: [
      [87.735709, 41.586145],
      [119.907027, 52.129584],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MNE',
    label: 'Montenegro',
    bounds: [
      [18.433531, 41.852362],
      [20.355171, 43.547886],
    ],
    renderAsPoint: true,
    markerCoordinates: [19.143727, 42.803101],
  },
  {
    iso3: 'MSR',
    label: 'Montserrat',
    bounds: [
      [-62.230133, 16.67536],
      [-62.140533, 16.819322],
    ],
    renderAsPoint: true,
    markerCoordinates: [-62.188252, 16.73717],
  },
  {
    iso3: 'MAR',
    label: 'Morocco',
    bounds: [
      [-17.013743, 21.419971],
      [-1.031999, 35.926519],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MOZ',
    label: 'Mozambique',
    bounds: [
      [30.213845, -26.860272],
      [40.847992, -10.469008],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MMR',
    label: 'Myanmar',
    bounds: [
      [92.174973, 9.790717],
      [101.173855, 28.538466],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NAM',
    label: 'Namibia',
    bounds: [
      [11.717621, -28.959368],
      [25.259781, -16.951057],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NRU',
    label: 'Nauru',
    bounds: [
      [166.906993, -0.551853],
      [166.958263, -0.490411],
    ],
    renderAsPoint: true,
    markerCoordinates: [166.932644, -0.520261],
  },
  {
    iso3: 'NPL',
    label: 'Nepal',
    bounds: [
      [80.030288, 26.343768],
      [88.169067, 30.416904],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NLD',
    label: 'Netherlands',
    bounds: [
      [3.349415, 50.74755],
      [7.198506, 53.558092],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NCL',
    label: 'New Caledonia',
    bounds: [
      [163.615733, -22.670668],
      [171.343765, -19.623712],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NZL',
    label: 'New Zealand',
    bounds: [
      [165.886485, -52.600313],
      [183.886119, -29.221938],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NIC',
    label: 'Nicaragua',
    bounds: [
      [-87.685821, 10.713482],
      [-82.725697, 15.03097],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NER',
    label: 'Niger',
    bounds: [
      [0.152941, 11.695773],
      [15.970322, 23.517351],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NGA',
    label: 'Nigeria',
    bounds: [
      [2.671082, 4.272162],
      [14.669936, 13.880291],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'NIU',
    label: 'Niue',
    bounds: [
      [-169.950429, -19.142755],
      [-169.782908, -18.964044],
    ],
    renderAsPoint: true,
    markerCoordinates: [-169.862565, -19.045956],
  },
  {
    iso3: 'NFK',
    label: 'Norfolk Island',
    bounds: [
      [167.91212, -29.080011],
      [167.996349, -28.997491],
    ],
    renderAsPoint: true,
    markerCoordinates: [167.954531, -29.033042],
  },
  {
    iso3: 'PRK',
    label: 'North Korea',
    bounds: [
      [124.211316, 37.675605],
      [130.699962, 43.01027],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'MKD',
    label: 'North Macedonia',
    bounds: [
      [20.444157, 40.849394],
      [23.009582, 42.370335],
    ],
    renderAsPoint: true,
    markerCoordinates: [21.555839, 41.558223],
  },
  {
    iso3: 'MNP',
    label: 'Northern Mariana Islands',
    bounds: [
      [144.90211, 14.110663],
      [145.868907, 20.555406],
    ],
    renderAsPoint: true,
    markerCoordinates: [145.734397, 15.188188],
  },
  {
    iso3: 'NOR',
    label: 'Norway',
    bounds: [
      [-9.117421, 57.99315],
      [31.076996, 71.180365],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'OMN',
    label: 'Oman',
    bounds: [
      [51.978615, 16.642401],
      [59.844574, 26.385972],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PAK',
    label: 'Pakistan',
    bounds: [
      [60.844379, 23.694525],
      [77.048971, 37.054484],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PLW',
    label: 'Palau',
    bounds: [
      [131.131114, 2.949042],
      [134.727343, 8.096618],
    ],
    renderAsPoint: true,
    markerCoordinates: [134.580157, 7.518252],
  },
  {
    iso3: 'PSE',
    label: 'Palestine',
    bounds: [
      [34.200269, 31.211449],
      [35.572536, 32.54264],
    ],
    renderAsPoint: true,
    markerCoordinates: [34.281082, 31.305615],
  },
  {
    iso3: 'PAN',
    label: 'Panama',
    bounds: [
      [-83.053246, 7.205715],
      [-77.16327, 9.629292],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PNG',
    label: 'Papua New Guinea',
    bounds: [
      [140.849211, -11.636326],
      [155.96754, -1.346368],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PRY',
    label: 'Paraguay',
    bounds: [
      [-62.650357, -27.586842],
      [-54.245289, -19.286729],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CHN',
    label: "People's Republic of China",
    bounds: [
      [73.602256, 18.169338],
      [134.772579, 53.569444],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PER',
    label: 'Peru',
    bounds: [
      [-81.337558, -18.337746],
      [-68.684252, -0.029093],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PHL',
    label: 'Philippines',
    bounds: [
      [116.954926, 4.655707],
      [126.617686, 21.122382],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PCN',
    label: 'Pitcairn Islands',
    bounds: [
      [-130.753082, -25.077081],
      [-124.778066, -23.924412],
    ],
    renderAsPoint: true,
    markerCoordinates: [-128.317536, -24.364576],
  },
  {
    iso3: 'POL',
    label: 'Poland',
    bounds: [
      [14.123923, 48.994013],
      [24.143156, 54.838324],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PRT',
    label: 'Portugal',
    bounds: [
      [-31.284901, 30.029242],
      [-6.205947, 42.15363],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'PRI',
    label: 'Puerto Rico',
    bounds: [
      [-67.937815, 17.922919],
      [-65.244618, 18.522773],
    ],
    renderAsPoint: true,
    markerCoordinates: [-66.481065, 18.234668],
  },
  {
    iso3: 'QAT',
    label: 'Qatar',
    bounds: [
      [50.750987, 24.559872],
      [51.616547, 26.160102],
    ],
    renderAsPoint: true,
    markerCoordinates: [51.143509, 25.237383],
  },
  {
    iso3: 'SRB',
    label: 'Republic of Serbia',
    bounds: [
      [18.844978, 42.234945],
      [22.984571, 46.173875],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'COG',
    label: 'Republic of the Congo',
    bounds: [
      [11.114016, -5.019631],
      [18.642407, 3.708276],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'REU',
    label: 'Réunion',
    bounds: [
      [55.225434, -21.370782],
      [55.854503, -20.861423],
    ],
    renderAsPoint: true,
    markerCoordinates: [55.535699, -21.113488],
  },
  {
    iso3: 'ROU',
    label: 'Romania',
    bounds: [
      [20.242826, 43.65005],
      [29.699555, 48.274832],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'RUS',
    label: 'Russia',
    bounds: [
      [19.609548, 41.192681],
      [191.005382, 81.85871],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'RWA',
    label: 'Rwanda',
    bounds: [
      [28.857236, -2.826855],
      [30.887809, -1.058694],
    ],
    renderAsPoint: true,
    markerCoordinates: [30.103894, -1.897196],
  },
  {
    iso3: 'BLM',
    label: 'Saint Barthélemy',
    bounds: [
      [-62.86734, 17.881985],
      [-62.791656, 17.929145],
    ],
    renderAsPoint: true,
    markerCoordinates: [-62.833193, 17.901987],
  },
  {
    iso3: 'SHN',
    label: 'Saint Helena, Ascension and Tristan da Cunha',
    bounds: [
      [-14.417714, -40.397882],
      [-5.65038, -7.877862],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'KNA',
    label: 'Saint Kitts and Nevis',
    bounds: [
      [-62.861073, 17.100531],
      [-62.536773, 17.415839],
    ],
    renderAsPoint: true,
    markerCoordinates: [-62.757975, 17.336558],
  },
  {
    iso3: 'LCA',
    label: 'Saint Lucia',
    bounds: [
      [-61.078521, 13.714667],
      [-60.882965, 14.111884],
    ],
    renderAsPoint: true,
    markerCoordinates: [-60.980094, 13.892371],
  },
  {
    iso3: 'MAF',
    label: 'Saint Martin',
    bounds: [
      [-63.14684, 18.033391],
      [-63.010732, 18.122138],
    ],
    renderAsPoint: true,
    markerCoordinates: [-63.049399, 18.081302],
  },
  {
    iso3: 'SPM',
    label: 'Saint Pierre and Miquelon',
    bounds: [
      [-56.396596, 46.752753],
      [-56.144765, 47.141262],
    ],
    renderAsPoint: true,
    markerCoordinates: [-56.332352, 47.040344],
  },
  {
    iso3: 'VCT',
    label: 'Saint Vincent and the Grenadines',
    bounds: [
      [-61.459828, 12.58515],
      [-61.123931, 13.380764],
    ],
    renderAsPoint: true,
    markerCoordinates: [-61.3359, 13.0879],
  },
  {
    iso3: 'WSM',
    label: 'Samoa',
    bounds: [
      [-172.782582, -14.05283],
      [-171.437693, -13.462823],
    ],
    renderAsPoint: true,
    markerCoordinates: [-172.438241, -13.639139],
  },
  {
    iso3: 'SMR',
    label: 'San Marino',
    bounds: [
      [12.385629, 43.892056],
      [12.492392, 43.982567],
    ],
    renderAsPoint: true,
    markerCoordinates: [12.441206, 43.933916],
  },
  {
    iso3: 'STP',
    label: 'São Tomé and Príncipe',
    bounds: [
      [6.461681, 0.024115],
      [7.462738, 1.699774],
    ],
    renderAsPoint: true,
    markerCoordinates: [7.021, 0.9709],
  },
  {
    iso3: 'SAU',
    label: 'Saudi Arabia',
    bounds: [
      [34.572765, 16.370958],
      [55.637565, 32.121348],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SEN',
    label: 'Senegal',
    bounds: [
      [-17.536041, 12.305607],
      [-11.377776, 16.691385],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SYC',
    label: 'Seychelles',
    bounds: [
      [46.207367, -9.755548],
      [56.287446, -3.791111],
    ],
    renderAsPoint: true,
    markerCoordinates: [55.480175, -4.676659],
  },
  {
    iso3: 'SLE',
    label: 'Sierra Leone',
    bounds: [
      [-13.301096, 6.91942],
      [-10.282236, 9.996006],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SGP',
    label: 'Singapore',
    bounds: [
      [103.640391, 1.264309],
      [104.003429, 1.448635],
    ],
    renderAsPoint: true,
    markerCoordinates: [103.816925, 1.366587],
  },
  {
    iso3: 'SXM',
    label: 'Sint Maarten',
    bounds: [
      [-63.118886, 18.01911],
      [-63.017569, 18.06212],
    ],
    renderAsPoint: true,
    markerCoordinates: [-63.070133, 18.04088],
  },
  {
    iso3: 'SVK',
    label: 'Slovakia',
    bounds: [
      [16.84448, 47.750006],
      [22.539637, 49.60178],
    ],
    renderAsPoint: true,
    markerCoordinates: [19.049868, 48.734044],
  },
  {
    iso3: 'SVN',
    label: 'Slovenia',
    bounds: [
      [13.365261, 45.423637],
      [16.515302, 46.863962],
    ],
    renderAsPoint: true,
    markerCoordinates: [14.915312, 46.06076],
  },
  {
    iso3: 'SLB',
    label: 'Solomon Islands',
    bounds: [
      [155.507986, -12.290623],
      [168.825857, -6.599867],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SOM',
    label: 'Somalia',
    bounds: [
      [40.965385, -1.696303],
      [51.417038, 11.989119],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ZAF',
    label: 'South Africa',
    bounds: [
      [16.469981, -46.965753],
      [37.977794, -22.126452],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SGS',
    label: 'South Georgia and the South Sandwich Islands',
    bounds: [
      [-38.087026, -59.472752],
      [-26.239329, -53.972426],
    ],
    renderAsPoint: true,
    markerCoordinates: [-31.063179, -55.683402],
  },
  {
    iso3: 'KOR',
    label: 'South Korea',
    bounds: [
      [124.613617, 33.197577],
      [131.862522, 38.578074],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SSD',
    label: 'South Sudan',
    bounds: [
      [24.121556, 3.490202],
      [35.920835, 12.216155],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'XSB',
    label: 'Sovereign Base Areas (Akrotiri and Dhekelia)',
    bounds: [
      [32.760102, 34.568549],
      [33.921474, 35.118994],
    ],
    renderAsPoint: true,
    markerCoordinates: [33.790583, 35.011042],
  },
  {
    iso3: 'ESP',
    label: 'Spain',
    bounds: [
      [-18.167226, 27.642239],
      [4.337087, 43.793443],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'LKA',
    label: 'Sri Lanka',
    bounds: [
      [79.655772, 5.923733],
      [81.89031, 9.829576],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SDN',
    label: 'Sudan',
    bounds: [
      [21.809449, 8.681642],
      [38.603852, 22.226965],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SUR',
    label: 'Suriname',
    bounds: [
      [-58.067691, 1.833507],
      [-53.986357, 6.011574],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SJM',
    label: 'Svalbard',
    bounds: [
      [10.484386, 74.347357],
      [33.640391, 80.770087],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'SWE',
    label: 'Sweden',
    bounds: [
      [11.108165, 55.342678],
      [24.163414, 69.036356],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'CHE',
    label: 'Switzerland',
    bounds: [
      [5.954809, 45.820718],
      [10.466627, 47.801166],
    ],
    renderAsPoint: true,
    markerCoordinates: [7.463965, 46.719114],
  },
  {
    iso3: 'SYR',
    label: 'Syria',
    bounds: [
      [35.723399, 32.313042],
      [42.377186, 37.324906],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TWN',
    label: 'Taiwan',
    bounds: [
      [118.279552, 21.904608],
      [122.005382, 25.287421],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TJK',
    label: 'Tajikistan',
    bounds: [
      [67.34269, 36.678641],
      [75.164125, 41.039977],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TZA',
    label: 'Tanzania',
    bounds: [
      [29.321032, -11.731272],
      [40.449392, -0.98583],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'THA',
    label: 'Thailand',
    bounds: [
      [97.351401, 5.62989],
      [105.650998, 20.445006],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'BHS',
    label: 'The Bahamas',
    bounds: [
      [-79.59435, 20.912399],
      [-72.746165, 26.928412],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GMB',
    label: 'The Gambia',
    bounds: [
      [-16.829701, 13.065009],
      [-13.818713, 13.819984],
    ],
    renderAsPoint: true,
    markerCoordinates: [-14.998318, 13.641721],
  },
  {
    iso3: 'TGO',
    label: 'Togo',
    bounds: [
      [-0.166109, 6.100491],
      [1.782351, 11.13498],
    ],
    renderAsPoint: true,
    markerCoordinates: [1.058113, 8.80722],
  },
  {
    iso3: 'TKL',
    label: 'Tokelau',
    bounds: [
      [-172.502553, -9.361749],
      [-171.185658, -8.543227],
    ],
    renderAsPoint: true,
    markerCoordinates: [-172.48629, -8.561824],
  },
  {
    iso3: 'TON',
    label: 'Tonga',
    bounds: [
      [-176.219309, -22.3388],
      [-173.914255, -15.559503],
    ],
    renderAsPoint: true,
    markerCoordinates: [-175.163014, -21.210026],
  },
  {
    iso3: 'TTO',
    label: 'Trinidad and Tobago',
    bounds: [
      [-61.9287, 10.04206],
      [-60.522084, 11.35106],
    ],
    renderAsPoint: true,
    markerCoordinates: [-60.9184, 10.9989],
  },
  {
    iso3: 'TUN',
    label: 'Tunisia',
    bounds: [
      [7.479832, 30.228905],
      [11.564131, 37.345201],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TUR',
    label: 'Turkey',
    bounds: [
      [25.663259, 35.819779],
      [44.806993, 42.098782],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TKM',
    label: 'Turkmenistan',
    bounds: [
      [52.437671, 35.140647],
      [66.645782, 42.791188],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'TCA',
    label: 'Turks and Caicos Islands',
    bounds: [
      [-72.481313, 21.290107],
      [-71.128896, 21.959215],
    ],
    renderAsPoint: true,
    markerCoordinates: [-71.752704, 21.81663],
  },
  {
    iso3: 'TUV',
    label: 'Tuvalu',
    bounds: [
      [176.125255, -9.420668],
      [179.906749, -5.677504],
    ],
    renderAsPoint: true,
    markerCoordinates: [179.209587, -8.513717],
  },
  {
    iso3: 'UGA',
    label: 'Uganda',
    bounds: [
      [29.54846, -1.475206],
      [35.006473, 4.219692],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'UKR',
    label: 'Ukraine',
    bounds: [
      [22.13284, 45.213568],
      [40.159543, 52.368949],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ARE',
    label: 'United Arab Emirates',
    bounds: [
      [51.569347, 22.620946],
      [56.383637, 26.074792],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'GBR',
    label: 'United Kingdom',
    bounds: [
      [-13.691314, 49.909613],
      [1.771169, 60.847886],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'USA',
    label: 'United States',
    bounds: [
      [172.476085, 18.395006],
      [293.022675, 71.412502],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'UMI',
    label: 'United States Minor Outlying Islands',
    bounds: [
      [114.02768, -0.388767],
      [199.991099, 28.215318],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'VIR',
    label: 'United States Virgin Islands',
    bounds: [
      [-65.041493, 17.682766],
      [-64.559397, 18.386599],
    ],
    renderAsPoint: true,
    markerCoordinates: [-64.779172, 17.746706],
  },
  {
    iso3: 'URY',
    label: 'Uruguay',
    bounds: [
      [-58.439361, -34.973403],
      [-53.110836, -30.09687],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'UZB',
    label: 'Uzbekistan',
    bounds: [
      [55.975839, 37.185147],
      [73.148641, 45.558719],
    ],
    renderAsPoint: true,
    markerCoordinates: [64.005429, 41.693603],
  },
  {
    iso3: 'VUT',
    label: 'Vanuatu',
    bounds: [
      [166.520518, -20.253106],
      [169.898936, -13.064874],
    ],
    renderAsPoint: true,
    markerCoordinates: [166.908762, -15.37153],
  },
  {
    iso3: 'VAT',
    label: 'Vatican City',
    bounds: [
      [12.452714, 41.902752],
      [12.454035, 41.903915],
    ],
    renderAsPoint: true,
    markerCoordinates: [12.453418, 41.903323],
  },
  {
    iso3: 'VEN',
    label: 'Venezuela',
    bounds: [
      [-73.391149, 0.649315],
      [-59.815595, 15.702948],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'VNM',
    label: 'Vietnam',
    bounds: [
      [102.118655, 8.565579],
      [109.472423, 23.366275],
    ],
    renderAsPoint: true,
    markerCoordinates: [105.387292, 21.715416],
  },
  {
    iso3: 'WLF',
    label: 'Wallis and Futuna',
    bounds: [
      [-178.18574, -14.319431],
      [-176.1256, -13.208917],
    ],
    renderAsPoint: true,
    markerCoordinates: [-178.137436, -14.286415],
  },
  {
    iso3: 'ESH',
    label: 'Western Sahara',
    bounds: [
      [-17.104644, 20.766913],
      [-8.680809, 27.661465],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'YEM',
    label: 'Yemen',
    bounds: [
      [42.545746, 12.111444],
      [54.540294, 18.995638],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ZMB',
    label: 'Zambia',
    bounds: [
      [21.979878, -18.069232],
      [33.674203, -8.194124],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
  {
    iso3: 'ZWE',
    label: 'Zimbabwe',
    bounds: [
      [25.21937, -22.39734],
      [33.042768, -15.614808],
    ],
    renderAsPoint: false,
    markerCoordinates: null,
  },
];
