-- Project map-field audit (read-only)
--
-- Purpose:
--   Reports country, status, and project-type values that can keep projects
--   off the overview map or prevent the proposed constraints from validating.
--
-- This script is read-only. Run each section independently in the Supabase SQL
-- editor or via psql. The canonical geography VALUES block is generated by:
--
--   pnpm generate:geographies
--
-- Do not edit the generated block by hand.

-- ============================================================================
-- Section 1: coverage summary
-- ============================================================================
SELECT
  count(*) AS total_projects,
  count(*) FILTER (WHERE project_status = 'Active') AS active_projects_exact,
  count(*) FILTER (
    WHERE lower(btrim(coalesce(project_status, ''))) = 'active'
      AND project_status IS DISTINCT FROM 'Active'
  ) AS active_status_variants,
  count(*) FILTER (
    WHERE project_status = 'Active'
      AND project_country IS NULL
  ) AS active_with_null_country,
  count(*) FILTER (
    WHERE project_status = 'Active'
      AND btrim(coalesce(project_country, '')) = ''
  ) AS active_with_blank_country,
  count(DISTINCT project_country) FILTER (
    WHERE project_country IS NOT NULL
      AND btrim(project_country) <> ''
  ) AS distinct_country_values_raw,
  count(DISTINCT lower(btrim(project_country))) FILTER (
    WHERE project_country IS NOT NULL
      AND btrim(project_country) <> ''
  ) AS distinct_country_values_normalised
FROM public.projects;

-- ============================================================================
-- Section 2: distinct country values and cleanup/sign-off flags
-- ============================================================================
WITH canonical_geographies(name) AS (
  VALUES
-- BEGIN GENERATED CANONICAL GEOGRAPHY VALUES
    ('Afghanistan'),
    ('Åland'),
    ('Albania'),
    ('Algeria'),
    ('American Samoa'),
    ('Andorra'),
    ('Angola'),
    ('Anguilla'),
    ('Antarctica'),
    ('Antigua and Barbuda'),
    ('Argentina'),
    ('Armenia'),
    ('Aruba'),
    ('Aruba, Bonaire, Curacao'),
    ('Australia'),
    ('Austria'),
    ('Azerbaijan'),
    ('Bahrain'),
    ('Bangladesh'),
    ('Barbados'),
    ('Belarus'),
    ('Belgium'),
    ('Belize'),
    ('Benin'),
    ('Bermuda'),
    ('Bhutan'),
    ('Bolivia'),
    ('Bosnia and Herzegovina'),
    ('Botswana'),
    ('Bouvet Island'),
    ('Brazil'),
    ('British Indian Ocean Territory'),
    ('British Virgin Islands'),
    ('Brunei'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Cambodia'),
    ('Cameroon'),
    ('Canada'),
    ('Cape Verde'),
    ('Caribbean Netherlands'),
    ('Cayman Islands'),
    ('Central African Republic'),
    ('Chad'),
    ('Chile'),
    ('Christmas Island'),
    ('Cocos'),
    ('Colombia'),
    ('Comoros'),
    ('Cook Islands'),
    ('Costa Rica'),
    ('Croatia'),
    ('Cuba'),
    ('Curaçao'),
    ('Cyprus'),
    ('Czech Republic'),
    ('Democratic Republic of the Congo'),
    ('Denmark'),
    ('Djibouti'),
    ('Dominica'),
    ('Dominican Republic'),
    ('Dutch Caribbean'),
    ('East Timor'),
    ('Ecuador'),
    ('Egypt'),
    ('El Salvador'),
    ('Equatorial Guinea'),
    ('Eritrea'),
    ('Estonia'),
    ('Eswatini'),
    ('Ethiopia'),
    ('Falkland Islands'),
    ('Faroe Islands'),
    ('Federated States of Micronesia'),
    ('Fiji'),
    ('Finland'),
    ('France'),
    ('French Guiana'),
    ('French Southern and Antarctic Lands'),
    ('Gabon'),
    ('Georgia'),
    ('Germany'),
    ('Ghana'),
    ('Gibraltar'),
    ('Greece'),
    ('Greenland'),
    ('Grenada'),
    ('Guadeloupe'),
    ('Guam'),
    ('Guatemala'),
    ('Guernsey'),
    ('Guinea'),
    ('Guinea-Bissau'),
    ('Guyana'),
    ('Haiti'),
    ('Heard Island and McDonald Islands'),
    ('Honduras'),
    ('Hong Kong'),
    ('Hungary'),
    ('Iceland'),
    ('India'),
    ('Indonesia'),
    ('Iran'),
    ('Iraq'),
    ('Ireland'),
    ('Isle of Man'),
    ('Israel'),
    ('Italy'),
    ('Ivory Coast'),
    ('Jamaica'),
    ('Japan'),
    ('Jersey'),
    ('Jordan'),
    ('Kazakhstan'),
    ('Kenya'),
    ('Kiribati'),
    ('Kosovo'),
    ('Kuwait'),
    ('Kyrgyzstan'),
    ('Laos'),
    ('Latvia'),
    ('Lebanon'),
    ('Lesotho'),
    ('Liberia'),
    ('Libya'),
    ('Liechtenstein'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Macau'),
    ('Madagascar'),
    ('Malawi'),
    ('Malaysia'),
    ('Maldives'),
    ('Mali'),
    ('Malta'),
    ('Marshall Islands'),
    ('Martinique'),
    ('Mauritania'),
    ('Mauritius'),
    ('Mayotte'),
    ('Mexico'),
    ('Moldova'),
    ('Monaco'),
    ('Mongolia'),
    ('Montenegro'),
    ('Montserrat'),
    ('Morocco'),
    ('Mozambique'),
    ('Myanmar'),
    ('Namibia'),
    ('Nauru'),
    ('Nepal'),
    ('Netherlands'),
    ('New Caledonia'),
    ('New Zealand'),
    ('Nicaragua'),
    ('Niger'),
    ('Nigeria'),
    ('Niue'),
    ('Norfolk Island'),
    ('North Korea'),
    ('North Macedonia'),
    ('Northern Mariana Islands'),
    ('Norway'),
    ('Oman'),
    ('Pakistan'),
    ('Palau'),
    ('Palestine'),
    ('Panama'),
    ('Papua New Guinea'),
    ('Paraguay'),
    ('People''s Republic of China'),
    ('Peru'),
    ('Philippines'),
    ('Pitcairn Islands'),
    ('Poland'),
    ('Portugal'),
    ('Puerto Rico'),
    ('Qatar'),
    ('Republic of Serbia'),
    ('Republic of the Congo'),
    ('Réunion'),
    ('Romania'),
    ('Russia'),
    ('Rwanda'),
    ('Saint Barthélemy'),
    ('Saint Helena, Ascension and Tristan da Cunha'),
    ('Saint Kitts and Nevis'),
    ('Saint Lucia'),
    ('Saint Martin'),
    ('Saint Pierre and Miquelon'),
    ('Saint Vincent and the Grenadines'),
    ('Samoa'),
    ('San Marino'),
    ('São Tomé and Príncipe'),
    ('Saudi Arabia'),
    ('Senegal'),
    ('Seychelles'),
    ('Sierra Leone'),
    ('Singapore'),
    ('Sint Maarten'),
    ('Slovakia'),
    ('Slovenia'),
    ('Solomon Islands'),
    ('Somalia'),
    ('South Africa'),
    ('South Georgia and the South Sandwich Islands'),
    ('South Korea'),
    ('South Sudan'),
    ('Sovereign Base Areas (Akrotiri and Dhekelia)'),
    ('Spain'),
    ('Sri Lanka'),
    ('Sudan'),
    ('Suriname'),
    ('Svalbard'),
    ('Sweden'),
    ('Switzerland'),
    ('Syria'),
    ('Taiwan'),
    ('Tajikistan'),
    ('Tanzania'),
    ('Thailand'),
    ('The Bahamas'),
    ('The Gambia'),
    ('Togo'),
    ('Tokelau'),
    ('Tonga'),
    ('Trinidad and Tobago'),
    ('Tunisia'),
    ('Tunisia, Libya'),
    ('Turkey'),
    ('Turkmenistan'),
    ('Turks and Caicos Islands'),
    ('Tuvalu'),
    ('Uganda'),
    ('Ukraine'),
    ('United Arab Emirates'),
    ('United Kingdom'),
    ('United States'),
    ('United States Minor Outlying Islands'),
    ('United States Virgin Islands'),
    ('Uruguay'),
    ('Uzbekistan'),
    ('Vanuatu'),
    ('Vatican City'),
    ('Venezuela'),
    ('Vietnam'),
    ('Wallis and Futuna'),
    ('Western Sahara'),
    ('Yemen'),
    ('Zambia'),
    ('Zimbabwe'),
    ('Ascension'),
    ('Channel Islands'),
    ('French Polynesia'),
    ('St Helena'),
    ('Dogger Bank'),
    ('Indian Ocean'),
    ('Mediterranean Sea'),
    ('North Sea'),
    ('Global')
-- END GENERATED CANONICAL GEOGRAPHY VALUES
),
known_aliases(raw_value, proposed_value, requires_signoff) AS (
  VALUES
    ('Ascension Island', 'Ascension', false),
    ('BVI', 'British Virgin Islands', false),
    ('England', NULL, true),
    ('Scotland', NULL, true),
    ('England, Scotland', NULL, true),
    ('French Polynseia', 'French Polynesia', false),
    ('Saint Helena', 'St Helena', false),
    ('St Helena Island', 'St Helena', false),
    ('Sao Tome', 'São Tomé and Príncipe', false),
    ('St Kitts and Nevis', 'Saint Kitts and Nevis', false),
    ('St Kitts & Nevis', 'Saint Kitts and Nevis', false),
    (
      'St Vincent and the Grenadines',
      'Saint Vincent and the Grenadines',
      false
    ),
    ('United Kingdom, EU', NULL, true)
),
country_counts AS (
  SELECT
    project_country AS raw_value,
    count(*) AS project_count,
    count(*) FILTER (WHERE project_status = 'Active') AS active_project_count
  FROM public.projects
  GROUP BY project_country
)
SELECT
  counts.raw_value,
  counts.project_count,
  counts.active_project_count,
  counts.raw_value IS NULL AS is_null,
  counts.raw_value IS NOT NULL
    AND btrim(counts.raw_value) = '' AS is_blank,
  counts.raw_value IS DISTINCT FROM btrim(counts.raw_value) AS has_outer_space,
  canonical.name IS NOT NULL AS is_canonical,
  alias.raw_value IS NOT NULL AS is_known_alias,
  alias.proposed_value,
  coalesce(alias.requires_signoff, false) AS requires_signoff,
  counts.raw_value IS NOT NULL
    AND btrim(counts.raw_value) <> ''
    AND canonical.name IS NULL
    AND alias.raw_value IS NULL AS is_unknown
FROM country_counts counts
LEFT JOIN canonical_geographies canonical
  ON canonical.name = btrim(counts.raw_value)
LEFT JOIN known_aliases alias
  ON alias.raw_value = btrim(counts.raw_value)
ORDER BY
  requires_signoff DESC,
  is_unknown DESC,
  has_outer_space DESC,
  counts.active_project_count DESC,
  counts.project_count DESC,
  counts.raw_value NULLS FIRST;

-- ============================================================================
-- Section 3: country values that differ only by case or outer whitespace
-- ============================================================================
SELECT
  lower(btrim(project_country)) AS normalised_value,
  array_agg(DISTINCT project_country ORDER BY project_country) AS raw_variants,
  count(*) AS project_count,
  count(*) FILTER (WHERE project_status = 'Active') AS active_project_count
FROM public.projects
WHERE project_country IS NOT NULL
  AND btrim(project_country) <> ''
GROUP BY lower(btrim(project_country))
HAVING count(DISTINCT project_country) > 1
ORDER BY project_count DESC, normalised_value;

-- ============================================================================
-- Section 4: status values
-- The validated CHECK permits Pipeline, Active, Complete, or NULL.
-- ============================================================================
SELECT
  project_status AS raw_value,
  count(*) AS project_count,
  project_status IS NULL AS is_null,
  project_status IS DISTINCT FROM btrim(project_status) AS has_outer_space,
  btrim(project_status) IN ('Pipeline', 'Active', 'Complete') AS is_canonical,
  false AS requires_signoff,
  project_status IS NOT NULL
    AND btrim(project_status) NOT IN (
      'Pipeline',
      'Active',
      'Complete'
    ) AS is_unknown
FROM public.projects
GROUP BY project_status
ORDER BY requires_signoff DESC, is_unknown DESC, project_count DESC, raw_value;

-- ============================================================================
-- Section 5: project-type values
-- ============================================================================
SELECT
  project_type AS raw_value,
  count(*) AS project_count,
  project_type IS NULL AS is_null,
  project_type IS DISTINCT FROM btrim(project_type) AS has_outer_space,
  btrim(project_type) IN (
    'Project',
    'Unit led project',
    'Unit'
  ) AS is_canonical,
  btrim(project_type) NOT IN (
    'Project',
    'Unit led project',
    'Unit'
  ) AS is_unknown
FROM public.projects
GROUP BY project_type
ORDER BY is_unknown DESC, project_count DESC, raw_value;
