-- Curated map headline stats (runtime editable content)
-- Source seed mapping: "Maerl landing page(Headline stats_Country).csv"

create table if not exists public.map_headline_stats (
  id bigint generated by default as identity primary key,
  geography_key text not null,
  display_template text not null,
  indicator_codes text[] not null default '{}',
  value_override numeric null,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint map_headline_stats_geography_key_format_chk
    check (geography_key ~ '^(c|w|sea|p|point):[a-z0-9-]+$'),
  constraint map_headline_stats_display_template_not_blank_chk
    check (btrim(display_template) <> ''),
  constraint map_headline_stats_value_or_indicators_chk
    check (value_override is not null or cardinality(indicator_codes) > 0),
  constraint map_headline_stats_unique_key_template_uq
    unique (geography_key, display_template)
);

create index if not exists map_headline_stats_enabled_sort_idx
  on public.map_headline_stats (enabled, sort_order, id);

create index if not exists map_headline_stats_geography_key_idx
  on public.map_headline_stats (geography_key);

create or replace function public.set_map_headline_stats_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists map_headline_stats_set_updated_at on public.map_headline_stats;

create trigger map_headline_stats_set_updated_at
before update on public.map_headline_stats
for each row
execute function public.set_map_headline_stats_updated_at();

alter table public.map_headline_stats enable row level security;

drop policy if exists "map_headline_stats_read_enabled" on public.map_headline_stats;
create policy "map_headline_stats_read_enabled"
on public.map_headline_stats
for select
to anon, authenticated
using (enabled = true);

insert into public.map_headline_stats (
  geography_key,
  display_template,
  indicator_codes,
  value_override,
  enabled,
  sort_order,
  notes
)
values
  ('c:gbr', 'x Ha under active resotration', array['2.2.5'], null, true, 10, null),
  ('c:gbr', 'x policies influenced', array['1.1.2', '2.1.2', '3.1.2', '4.1.2'], null, true, 20, null),
  ('c:gbr', 'x laws or legal agreeements influenced', array['4.3.2'], null, true, 30, null),
  ('c:gbr', 'x MPAs with improved management', array['1.3.1', '1.3.2'], null, true, 40, null),
  ('c:gbr', 'x sq km under protection commitments', array['1.2.1'], null, true, 50, null),

  ('p:channel-islands', 'x sq km free from destructive fishing', array['4.2.1'], null, true, 60, null),
  ('p:ascension', 'x sq km protected', array['1.2.2'], null, true, 70, null),
  ('p:st-helena', 'x sq km protected', array['1.2.2'], null, true, 80, null),

  ('c:ita', 'x MPAs with new management measures', array['1.3.1'], null, true, 90, null),
  ('c:grc', 'x sq km protected from harmful practices', array['1.2.2'], null, true, 100, null),
  ('c:grc', 'x stakeholders supported', array['5.2.1', '5.2.2'], null, true, 110, null),

  ('w:mediterranean-sea', 'x shark species under improved management', array['4.2.2'], null, true, 120, null),
  ('c:ata', 'x e-actions taken', array['5.3.3'], null, true, 130, null),

  ('p:barbados', 'x sq km protected', array['1.2.2'], null, true, 140, null),
  ('p:barbados', 'x people trained', array['5.5.1'], null, true, 150, null),

  ('c:dom', 'x sq km protected', array['1.2.2'], null, true, 160, null),

  ('c:cuw', 'x km protected', array['1.2.3'], null, true, 170, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:abw', 'x km protected', array['1.2.3'], null, true, 171, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:sxm', 'x km protected', array['1.2.3'], null, true, 172, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:bes', 'x km protected', array['1.2.3'], null, true, 173, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:cuw', 'x sustainable financing plans developed', array['1.1.1'], null, true, 174, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:abw', 'x sustainable financing plans developed', array['1.1.1'], null, true, 175, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:sxm', 'x sustainable financing plans developed', array['1.1.1'], null, true, 176, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:bes', 'x sustainable financing plans developed', array['1.1.1'], null, true, 177, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:cuw', 'x people reached through knowledge sharing and collaboration', array['5.2.2'], null, true, 178, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:abw', 'x people reached through knowledge sharing and collaboration', array['5.2.2'], null, true, 179, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:sxm', 'x people reached through knowledge sharing and collaboration', array['5.2.2'], null, true, 180, 'Dutch Caribbean headline replicated across mapped islands'),
  ('c:bes', 'x people reached through knowledge sharing and collaboration', array['5.2.2'], null, true, 181, 'Dutch Caribbean headline replicated across mapped islands'),

  ('p:st-vincent-and-the-grenadines', 'x sq km under sustainable management', array['4.2.1'], null, true, 190, null),
  ('c:nam', 'x Govt staff and tehcnical personnel trained', array['5.2.2'], null, true, 200, null),
  ('c:idn', 'x local Papuans trained as dive guides', array['5.2.2'], null, true, 210, null),
  ('c:moz', 'x women trained in sustainble aquaculture', array['5.2.2'], null, true, 220, null),
  ('c:phl', 'x people trained in mangrove restoration techniques', array['5.2.1'], null, true, 230, null),
  ('c:arg', 'x sq km protected', array['1.2.2'], null, true, 240, null),
  ('c:bra', 'x sq km protected', array['1.2.2'], null, true, 250, null),
  ('c:chl', 'x sq km protected', array['1.2.2'], null, true, 260, null),
  ('c:mex', 'x fishers transitioned from fishing to shark tourism', array['5.2.1'], null, true, 270, null),
  ('c:ury', 'x sq km protected', array['1.2.2'], null, true, 280, null),
  ('c:ury', 'x people reached through educational activities', array['5.5.1'], null, true, 290, null)
on conflict (geography_key, display_template) do update
set
  indicator_codes = excluded.indicator_codes,
  value_override = excluded.value_override,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  notes = excluded.notes,
  updated_at = now();
